//settingPage
export const SETTING_ACCOUNT = 'SETTING_ACCOUNT'
export const SETTING_NOTIFICATION = 'SETTING_NOTIFICATION'
export const SETTING_EDITREGIMEN = 'SETTING_EDITREGIMEN'
export const SETTING_ABOUT = 'SETTING_ABOUT'
export const SETTING_SUPPORT = 'SETTING_SUPPORT'

//regimen Page
export const REGIMEN_INFUSIONCYCLE = 'REGIMEN_INFUSIONCYCLE'
export const REGIMEN_INFUSIONNUM = 'REGIMEN_INFUSIONNUM'
export const REGIMEN_DATE = 'REGIMEN_DATE'
export const REGIMEN_INFUSIONLIST = 'REGIMEN_INFUSIONLIST'
export const REGIMEN_LASTINFUSION = 'REGIMEN_LASTINFUSION'

//Data Page
export const SYMPTOM_OBSERVATION = 'SYMPTOM_OBSERVATION'

//setting Page
export const EFFECT_FATIGUE = 'EFFECT_FATIGUE'
export const EFFECT_ANXIETY = 'EFFECT_ANXIETY'
export const EFFECT_CLICKED_FATIGUE = 'EFFECT_CLICKED_FATIGUE'
export const EFFECT_CLICKED_ANXIETY = 'EFFECT_CLICKED_ANXIETY'
export const ADD_SYMPTOMS = 'ADD_SYMPTOMS'

//login page
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL'
export const SIGNUP_PASSWORD = 'SIGNUP_PASSWORD'
export const SIGNUP_USERINFO = 'SIGNUP_USERINFO'

//overview
export const OVERVIEW_AVERAGEFATIGUE = 'OVERVIEW_AVERAGEFATIGUE'
export const OVERVIEW_AVERAGEANXIETY = 'OVERVIEW_AVERAGEANXIETY'


