export const FETCHING_PEOPLE = 'FETCHING_PEOPLE'
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE'

//settingPage
export const SETTING_ACCOUNT = 'SETTING_ACCOUNT'
export const SETTING_NOTIFICATION = 'SETTING_NOTIFICATION'
export const SETTING_EDITREGIMEN = 'SETTING_EDITREGIMEN'
export const SETTING_ABOUT = 'SETTING_ABOUT'
export const SETTING_SUPPORT = 'SETTING_SUPPORT'

//Setting Regimen Information
export const SET_PAGE_VIEW = 'SET_PAGE_VIEW'
export const SET_NUM_TREATMENTS = "SET_NUM_TREATMENTS"
export const SET_INTER_TREATMENT_INTERVAL = "SET_INTER_TREATMENT_INTERVAL"
export const SET_TREATMENT_START_DATE = "SET_TREATMENT_START_DATE"
